from odoo import models, fields, api
from odoo.exceptions import ValidationError


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    @api.constrains('name')
    def _check_unique_name_default_code(self):
        for record in self:
            # Check if there's any other product with the same name
            if self.search([('name', '=', record.name), ('id', '!=', record.id)]):
                raise ValidationError("Product name must be unique.")

    default_code = fields.Char(
        'INT_REF1', compute='_compute_default_code',
        inverse='_set_default_code', store=True)
    int_ref2 = fields.Char(string='INT_REF2')
    cod = fields.Char(string='COD')
    execution = fields.Char(string='EXECUTION')
    stdtype = fields.Char(string='STDTYPE')
    firma = fields.Char(string='FIRMA')
    standard = fields.Char(string='STANDARD')
    typestd1 = fields.Char(string='TYPESTD1')
    face = fields.Char(string='FACE')
    facefinish = fields.Char(string='FACEFINISH')
    standard2 = fields.Char(string='STANDARD2')
    end = fields.Char(string='END')
    end2 = fields.Char(string='END2')
    end3 = fields.Char(string='END3')

    control = fields.Char(string='CONTROL')
    mat_group = fields.Char(string='MAT_GROUP')
    material = fields.Char(string='MATERIAL')
    finish = fields.Char(string='FINISH')
    material2 = fields.Char(string='MATERIAL2')
    finish2 = fields.Char(string='FINISH2')
    d1c = fields.Char(string='D1C')
    d2c = fields.Char(string='D2C')
    dms = fields.Char(string='DMS')

    dimension = fields.Char(string='DIMENSION')
    dimension2 = fields.Char(string='DIMENSION2')
    profildim = fields.Char(string='PROFILDIM')
    rt = fields.Char(string='RT')
    rl = fields.Char(string='RL')
    rlrs = fields.Char(string='RLRS')
    scut = fields.Char(string='SCUT')
    dgr = fields.Char(string='DGR')
    dn1 = fields.Integer(string='DN1')
    dn2 = fields.Integer(string='DN2')
    dn3 = fields.Integer(string='DN3')
    dn1u = fields.Char(string='DN1U')
    dn2u = fields.Char(string='DN2U')
    dn3u = fields.Char(string='DN3U')
    pn1 = fields.Char(string='PN1')
    pn2 = fields.Char(string='PN2')
    pn1u = fields.Char(string='PN1U')
    pn2u = fields.Char(string='PN2U')
    sch1 = fields.Char(string='SCH1')
    sch2 = fields.Char(string='SCH2')
    sdr = fields.Char(string='SDR')
    od1 = fields.Float(string='OD1')
    od2 = fields.Float(string='OD2')
    od3 = fields.Float(string='OD3')
    wt1 = fields.Float(string='WT1')
    wt2 = fields.Float(string='WT2')
    wt3 = fields.Float(string='WT3')
    diaext = fields.Char(string='DIAEXT')
    diaext2 = fields.Char(string='DIAEXT2')
    diaint = fields.Char(string='DIAINT')
    diaint2 = fields.Char(string='DIAINT2')
    diac = fields.Char(string='DIAC')
    bore = fields.Char(string='BORE')
    diabolt = fields.Char(string='DIABOLT')
    boltl = fields.Char(string='BOLTL')
    studl = fields.Char(string='STUDL')
    boltno = fields.Char(string='BOLTNO')
    threadt = fields.Char(string='THREADT')
    thread = fields.Char(string='THREAD')
    th1 = fields.Char(string='TH1')
    th2 = fields.Char(string='TH2')
    len1 = fields.Char(string='LEN1')
    len1rs = fields.Char(string='LEN1RS')
    len2 = fields.Integer(string='LEN2')
    wid1 = fields.Char(string='WID1')
    wid2 = fields.Char(string='WID2')
    hig1 = fields.Char(string='HIG1')
    hig2 = fields.Char(string='HIG2')
    a = fields.Char(string='A')
    b = fields.Char(string='B')
    c = fields.Char(string='C')
    d = fields.Char(string='D')
    e = fields.Char(string='E')
    f = fields.Char(string='F')
    g = fields.Char(string='G')
    prefab = fields.Char(string='PREFAB')
    mh = fields.Char(string='MH')
    surface = fields.Char(string='SURFACE')

    inch_zv = fields.Char(string='INCH_ZV')
    kg_zv = fields.Char(string='KG_ZV')
    inch_mont = fields.Char(string='INCH_MONT')
    kg_mont = fields.Char(string='KG_MONT')
    mhzv = fields.Char(string='MHZV')
    mhmont = fields.Char(string='MHMONT')
