from odoo import models, fields, api
from odoo.exceptions import ValidationError


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    @api.constrains('name')
    def _check_unique_name_default_code(self):
        for record in self:
            # Check if there's any other product with the same name
            if self.search([('name', '=', record.name), ('id', '!=', record.id)]):
                raise ValidationError("Product name must be unique.")

    default_code = fields.Char(
        'INT_REF1', compute='_compute_default_code',
        inverse='_set_default_code', store=True)
    int_ref2 = fields.Char(string='INT_REF2')
    #specification
    cod = fields.Char(string='COD',index=True)
    execution = fields.Char(string='EXECUTION',index=True)
    stdtype = fields.Char(string='STDTYPE',index=True)
    firma = fields.Char(string='FIRMA',index=True)
    standard = fields.Char(string='STANDARD',index=True)
    typestd1 = fields.Char(string='TYPESTD1',index=True)
    face = fields.Char(string='FACE',index=True)
    facefinish = fields.Char(string='FACEFINISH',index=True)
    standard2 = fields.Char(string='STANDARD2', index=True)
    end = fields.Char(string='END', index=True)
    end2 = fields.Char(string='END2', index=True)
    end3 = fields.Char(string='END3', index=True)

    control = fields.Char(string='CONTROL', index=True)
    mat_group = fields.Char(string='MAT_GROUP', index=True)
    material = fields.Char(string='MATERIAL', index=True)
    finish = fields.Char(string='FINISH', index=True)
    material2 = fields.Char(string='MATERIAL2', index=True)
    finish2 = fields.Char(string='FINISH2', index=True)
    d1c = fields.Char(string='D1C', index=True)
    d2c = fields.Char(string='D2C', index=True)
    dms = fields.Char(string='DMS', index=True)

    dimension = fields.Char(string='DIMENSION', index=True)
    dimension2 = fields.Char(string='DIMENSION2', index=True)

    #properties
    profildim = fields.Char(string='PROFILDIM', index=True)
    rt = fields.Char(string='RT', index=True)
    rl = fields.Char(string='RL', index=True)
    rlrs = fields.Char(string='RLRS', index=True)
    scut = fields.Char(string='SCUT', index=True)
    dgr = fields.Char(string='DGR',index=True)
    dn1 = fields.Char(string='DN1', index=True)
    dn2 = fields.Char(string='DN2', index=True)
    dn3 = fields.Char(string='DN3', index=True)
    dn1u = fields.Char(string='DN1U', index=True)
    dn2u = fields.Char(string='DN2U', index=True)
    dn3u = fields.Char(string='DN3U', index=True)
    pn1 = fields.Char(string='PN1', index=True)
    pn2 = fields.Char(string='PN2', index=True)
    pn1u = fields.Char(string='PN1U', index=True)
    pn2u = fields.Char(string='PN2U', index=True)
    sch1 = fields.Char(string='SCH1', index=True)
    sch2 = fields.Char(string='SCH2', index=True)
    sdr = fields.Char(string='SDR', index=True)
    od1 = fields.Float(string='OD1')
    od2 = fields.Float(string='OD2')
    od3 = fields.Float(string='OD3')
    wt1 = fields.Float(string='WT1')
    wt2 = fields.Float(string='WT2')
    wt3 = fields.Float(string='WT3')
    diaext = fields.Char(string='DIAEXT', index=True)
    diaext2 = fields.Char(string='DIAEXT2', index=True)
    diaint = fields.Char(string='DIAINT', index=True)
    diaint2 = fields.Char(string='DIAINT2', index=True)
    diac = fields.Char(string='DIAC', index=True)
    bore = fields.Char(string='BORE', index=True)
    diabolt = fields.Char(string='DIABOLT', index=True)
    boltl = fields.Char(string='BOLTL', index=True)
    studl = fields.Char(string='STUDL', index=True)
    boltno = fields.Char(string='BOLTNO', index=True)
    threadt = fields.Char(string='THREADT', index=True)
    thread = fields.Char(string='THREAD', index=True)
    th1 = fields.Char(string='TH1', index=True)
    th2 = fields.Char(string='TH2', index=True)
    len1 = fields.Char(string='LEN1', index=True)
    len1rs = fields.Char(string='LEN1RS', index=True)
    len2 = fields.Integer(string='LEN2')
    wid1 = fields.Char(string='WID1', index=True)
    wid2 = fields.Char(string='WID2', index=True)
    hig1 = fields.Char(string='HIG1',index=True)
    hig2 = fields.Char(string='HIG2', index=True)
    a = fields.Char(string='A',index=True)
    b = fields.Char(string='B', index=True)
    c = fields.Char(string='C', index=True)
    d = fields.Char(string='D', index=True)
    e = fields.Char(string='E', index=True)
    f = fields.Char(string='F', index=True)
    g = fields.Char(string='G', index=True)
    prefab = fields.Char(string='PREFAB', index=True)
    mh = fields.Char(string='MH', index=True)
    surface = fields.Char(string='SURFACE', index=True)
    #work time
    inch_zv = fields.Char(string='INCH_ZV',index=True)
    kg_zv = fields.Char(string='KG_ZV', index=True)
    inch_mont = fields.Char(string='INCH_MONT', index=True)
    kg_mont = fields.Char(string='KG_MONT', index=True)
    mhzv = fields.Char(string='MHZV', index=True)
    mhmont = fields.Char(string='MHMONT', index=True)
